all : test1 test2 test3 test4 test5 test6 test7

test1 : test1.c slug_mem.c slug_mem.h
	gcc -o test1 test1.c slug_mem.c -lm

test2 : test2.c slug_mem.c slug_mem.h
	gcc -o test2 test2.c slug_mem.c -lm

test3 : test3.c slug_mem.c slug_mem.h
	gcc -o test3 test3.c slug_mem.c -lm

test4 : test4.c slug_mem.c slug_mem.h
	gcc -o test4 test4.c slug_mem.c -lm

test5 : test5.c slug_mem.c slug_mem.h
	gcc -o test5 test5.c slug_mem.c -lm

test6: test6.c slug_mem.c slug_mem.h
	gcc -o test6 test6.c slug_mem.c -lm

test7: test7.c slug_mem.c slug_mem.h
	gcc -o test7 test7.c slug_mem.c -lm
clean :
	rm test[0-9]
